on: [push, pull_request]

name: Testing

env:
  NOTION_RSS_KEY: ${{ secrets.NOTION_API_TOKEN }}

  # Required: Manually share database with the notion integration with api key `NOTION_RSS_KEY`.
  NOTION_RSS_CONTENT_DATABASE_ID: "18bf46e18ef6460fa4097334b42186d5"
  NOTION_RSS_FEEDS_DATABASE_ID: "ad0e953d68f34c5fb628a90d48105591"

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check-go-fmt
        run: test -z `go fmt ./...`
      - name: test
        run: go test ./...

  integration-tests:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: integration-tests
        run: echo "Write some integration tests"
